version: '3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: srs_db
      MYSQL_USER: srs_db
      MYSQL_PASSWORD: srs_passwd
    ports:
      - "3306"
  srs:
    build: .
    image: shopping-rest-service
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_PASSWORD: srs_passwd
    depends_on:
      - db
    links:
      - db:mysql
    ports:
      - "8080"
