version: '2'
networks:
  srs_test_net:
    driver: bridge
services:
  db_test:
    image: mariadb
    networks:
      - srs_test_net
    env_file: ../../shoppinglist-config/mysql/test.env
    ports:
      - "127.0.0.1:3309:3306"
  srs_test:
    networks:
      - srs_test_net
    image: cwr10010docker/shoppinglist-rest-service
    environment:
      SPRING_PROFILES_ACTIVE: test
    volumes:
      - "../../shoppinglist-config/spring/config:/app/config"
      - "../logs:/app/logs"
    depends_on:
      - db_test
    links:
      - db_test:mysql
    ports:
      - "127.0.0.1:8089:8080"
